### ISSUE TITLE
DECDLD soft font definition sequence fails when the last parameter is omitted

### ISSUE THREAD

**Issue by jtsiomb** [arakiken/mlterm#103]
Unless I'm misreading the DEC documentation, any command sequence can leave out parameters which do not need to be changed from their default value. In my terminal tetris program (https://github.com/jtsiomb/termtris), which uses DECDLD to download custom characters for the tetris blocks, I used to omit the last parameter (Pcss, character set size). This worked fine on all DEC terminals I tested on (vt220, vt320, vt420), and the windows terminal emulator, but fails to upload the custom characters to mlterm.

If you want to test this, try running termtris 1.9 in mlterm: https://github.com/jtsiomb/termtris/releases/tag/v1.9

The last git revision of termtris will work correctly with mlterm, because I side-stepped the issue by explicitly transmitting all parameters. But I think the behaviour in mlterm should also be corrected so that such a workaround is not necessary.

**Comment by arakiken** [comment]
Thank you.
As you pointed out, Pcmh and Pcss of DECDLD are omittable according to https://vt100.net/docs/vt510-rm/DECDLD.html.
I fixed. -> https://github.com/arakiken/mlterm/commit/2daa4e930a3d432361484b44d4920ed4d5246673
