### ISSUE TITLE
Spelling fixes

### ISSUE THREAD

**Issue by tsutsui** [arakiken/mlterm#107]
I notice ubuntu has their own diffs to fix `s/splitted/split/g` spelling in several files:
https://git.launchpad.net/ubuntu/+source/mlterm/commit/?h=applied/ubuntu/noble&id=ca222e7f6ae4f4fee81b625fac325c50142da967

**Comment by arakiken** [comment]
Thanks. I merged it. https://github.com/arakiken/mlterm/commit/d9e8b10d9bf9ea4870a9dd46ca54da1ed80e0ebe
