### ISSUE TITLE
`configure` doesn't show a result of `utmp`?

### ISSUE THREAD

**Issue by tsutsui** [arakiken/mlterm#111]
`configure.in` has the following line to show a result of checks about `utmp`:
https://github.com/arakiken/mlterm/blob/92fa70f1da41fb2c8affd387e775d95f3e75ead4/configure.in#L2429

but it looks the variable `$utmp` is not set anywhere and each log in github actions shows nothing.

Furthermore, `configure.in` treats `setutxent()` as SysV, but it has been in the POSIX (since 2001):
https://pubs.opengroup.org/onlinepubs/007908799/xsh/setutxent.html
https://pubs.opengroup.org/onlinepubs/009695399/functions/setutxent.html
https://pubs.opengroup.org/onlinepubs/9699919799/functions/setutxent.html
https://pubs.opengroup.org/onlinepubs/9799919799/functions/setutxent.html

so I wonder if we should prefer it rather than `utempter_add_record(3)` derived from Linux that requires extra libraries.
https://manpages.debian.org/unstable/libutempter-dev/utempter_add_record.3.en.html

**Comment by tsutsui** [comment]
Now I see `utempter_add_record(3)` doesn't require setuid but POSIX `setutxent()` might require setuid on *certain* systems (though NetBSD doesn't), so the following lines are invalid and I'd withdraw it.
> so I wonder if we should prefer it rather than `utempter_add_record(3)` derived from Linux that requires extra libraries.

**Comment by arakiken** [comment]
Thanks. I changed "utmp support" message from $utmp to $UTMP_NAME.
https://github.com/arakiken/mlterm/commit/de4b0f7216aaf53756d0b94b6fb0c448c9c10a83

**Comment by tsutsui** [comment]
Confirmed. Thanks!
```
utmp support                      : sysv
```
