### ISSUE TITLE
`libind/lex.split.c` is always generated unintentionally?

### ISSUE THREAD

**Issue by tsutsui** [arakiken/mlterm#112]
In https://github.com/arakiken/mlterm/commit/0a0076556317962630ea21e601a98499eb830584 `libind/lex.split.c` has been renamed to `libind/libind_lex.split.c`.

However `libind/lex.split.c` was not in `TBL_OBJ` and the target definition of `lex.split.c` was not changed.
https://github.com/arakiken/mlterm/blob/0a0076556317962630ea21e601a98499eb830584/libind/Makefile.in#L22-L25
https://github.com/arakiken/mlterm/blob/0a0076556317962630ea21e601a98499eb830584/libind/Makefile.in#L64-L67

It looks it should not have been changed, otherwise `lex.split.c` is always regenerated using lex(1).

**Comment by arakiken** [comment]
Thanks. I fixed it.
https://github.com/arakiken/mlterm/commit/a83539ad7ba2952c320495bcc995826e189d865b

**Comment by tsutsui** [comment]
Confirmed, thanks!
