### ISSUE TITLE
backspace key does not work in Emacs

### ISSUE THREAD

**Issue by linwaytin** [arakiken/mlterm#116]
I use mlterm under Linux. It seems by default mlterm sends `Ctrl+h` when pressing backspace key. `Ctrl+h` key has other functionality in emacs, and I want backspace can delete the previous character, as it should be. 

What is the correctly to change the default key sequence? Thank you.

**Comment by mckellygit** [comment]
Hi,
Maybe you could try adding this to the config file ~/.mlterm/key 
```
BackSpace="\x7f"
```

**Comment by mckellygit** [comment]
Maybe also what does your
```
stty -a
```
show for the erase key

**Comment by linwaytin** [comment]
`stty -a` gives me
```
speed 38400 baud; rows 35; columns 146; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
rprnt = ^R; werase = ^W; lnext = <undef>; discard = <undef>; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

**Comment by linwaytin** [comment]
`BackSpace="\x7f"` seems to work. Could you please explain more about this? What does "\x7f" represent? Thanks a lot.

**Comment by mckellygit** [comment]
Hi,
This sends hex 7f on BackSpace instead of sending Ctrl+h (8).
7f is the DEL char.
-m

**Comment by linwaytin** [comment]
Thank you!
