### ISSUE TITLE
mlterm fails to start mlconfig built with GTK4

### ISSUE THREAD

**Issue by fumiyas** [arakiken/mlterm#117]
mlterm invokes `mlconfig --geometry ...`, but mlconfig built with GTK4 does not support `--geometry` option.

[#1066997 - mlterm cannot launch mlconfig because it doesn’t support --geometry - Debian Bug report logs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1066997)

**Comment by arakiken** [comment]
Thank you.
This problem has been already fixed. -> https://github.com/arakiken/mlterm/commit/157d8179f8dda0d75ee179d1f1160770228f98f4
I'm currently preparing for the next release. It takes some time, sorry.
