### ISSUE TITLE
drawing error with `nvim`

### ISSUE THREAD

**Issue by atondwal** [arakiken/mlterm#15]
Last line seems to draw incorrectly and wrap when using `nvim` (this example has me repeatedly typing `o<Esc>` in an empty file). Doesn't seem to happen with any other terminal emulator. Happens with empty `init.vim` and `.mlterm` configurations.

![nvim](https://user-images.githubusercontent.com/343048/115102607-c6db2880-9f00-11eb-85f9-c1c814b4ddab.gif)

```
mlterm version 3.9.1 post/2021-04-09
Features: otl ssh implugin imagelib(builtin) utmp
```
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```

**Comment by atondwal** [comment]
bisect implicates `34a54dae514f20ce2f1d7b847092fe0ffbdcfeee`

**Comment by atondwal** [comment]
Ah, this is a matter of control characters! Since `xterm` accepts any of the U+0000 block control characters `0x00`-`0x1F` for escape sequences, when our `TERM=xterm`, nvim will use them. This can solved for me by either setting `TERM=kterm` (or `urxvt`, `st`, etc...) or by editing

https://github.com/arakiken/mlterm/blob/93a26d3949cf6837651b5db399731614b04d3e01/vtemu/vt_parser.c#L4347

to include the additional condition `**str < 0x20 ||`. Setting `TERM` solves the problem for me, so feel free to close, but if you want to maintain compatibility with `xterm`'s termcap/info, might be worth fixing this.

**Comment by arakiken** [comment]
Thanks very much.

I'd like to understand the cause of this problem, but I couldn't reproduce it in my environment
(nvim 0.4.4, mlterm-3.9.1 on arch linux).
I think that it doesn't fix incompatiblity with xterm completely to add '**str < 0x20' to get_pt_in_esc_seq(),
I'm wondering how to fix it with another approach.

Would you start mlterm with --logseq option and send me ~/.mlterm/*.log ?
It will help me reproduce the problem.
If possible, I'd like to see the result of 'infocmp xterm' command on your system.

Regards,

**Comment by atondwal** [comment]
Thanks for the response! I'm also using nvim 0.4.4 on arch linux (seeing this with both mlterm-3.9.1 as well as `master` on a fresh arch install installed from the AUR
[pts_11-20210420084942.log](https://github.com/arakiken/mlterm/files/6344924/pts_11-20210420084942.log)
)
[xterm.infocmp.txt](https://github.com/arakiken/mlterm/files/6344820/xterm.infocmp.txt)

**Comment by arakiken** [comment]
Thanks to your help, I found that mlterm-3.9.1 or before failed to parse OSC sequence which doesn't contain semicolon.
I fixed it, so I'd like you to test it.

https://github.com/arakiken/mlterm/commit/48e78654e0c6fe5399a589d4b8dd49e5d9b0765d#diff-c9af0817cb9fcedacbeb3ec34e3d026ce4da2ce96eda2bf96b76043ae8de0e6b

**Comment by atondwal** [comment]
Works great now!
