### ISSUE TITLE
Paste CLIPBOARD content

### ISSUE THREAD

**Issue by Atemu** [arakiken/mlterm#19]
Currently, mlterm allows the user to paste the PRIMARY clipboard via `S-<insert>`.

I often copy text in Emacs without selecting it visually via a shortcut which means that its content is "stored" in CLIPBOARD instead of PRIMARY, making me unable to paste it into mlterm.

Since CLIPBOARD is the go-to clipboard that's used in basically all other programs for `C-c` `C-v` etc., it'd be very helpful if mlterm also had a (preferably rebindable) keyboard shortcut for pasting its content.

**Comment by arakiken** [comment]
I added INSERT_CLIPBOARD shortcut key which is not assigned to any key by default.
https://github.com/arakiken/mlterm/commit/f863ca55b9d92a0b7a36746a7d7893fdf44234a5

For example, the following setting enables you to copy from CLIPBOARD by pressing Shift+Control+Insert
~/.mlterm/key
Shift+Control+Insert=INSERT_CLIPBOARD

**Comment by Atemu** [comment]
Thank you so much, that works brilliantly!

Might not be a bad idea to set a default shortcut to C-V or similar since that's what most users will be used to from mainstream terminal emulators like GNOME terminal, Konsole etc.

**Comment by kajzersoze** [comment]
Seems like this isn't working in Wayland version (`mlterm-wl`) , I can confirm it worked in `mlterm`

**Comment by arakiken** [comment]
Thanks.
INSERT_CLIPBOARD shortcut is now available in mlterm-wl.
https://github.com/arakiken/mlterm/commit/c87f20d8dac141f9848570179428bf8b2cdc7689

**Comment by TheMainMMan** [comment]
Works, thanks!
