### ISSUE TITLE
MLterm makes cursor visible after displaying sixel

### ISSUE THREAD

**Issue by dankamongmen** [arakiken/mlterm#24]
Through at least version 3.9.0, after a Sixel is displayed in MLterm, the cursor is made visible, even if it was hidden before. This behavior is, so far as I can tell, unique to MLterm. It would be appreciated if the previous cursor state were retained.

**Comment by arakiken** [comment]
Sorry, I couldn't reproduce it.
(I used CSI?25l to hide the cursor and showed sixel graphics, but the cursor remained hidden.)
Will you try it again with --logseq option and send me ~/.mlterm/xxxx-YYYYMMDDHHMMSS.log file ?

**Comment by dankamongmen** [comment]
sure, i'll try to get that to you within a few hours

**Comment by dankamongmen** [comment]
[pts_4-20210626231813.log.txt](https://github.com/arakiken/mlterm/files/6720965/pts_4-20210626231813.log.txt)

**Comment by arakiken** [comment]
Thanks.

Please look at the last 3 lines of the log. => http://mlterm.sourceforge.net/pts_4-20210626231813-2.log
^[[?25h which is output before "Aborted (core dump)" makes the cursor visible.
If I do 'cat pts_4-20210626231813.log.txt' on other terminals such as xterm, the cursor becomes visible.

I haven't investigate https://github.com/dankamongmen/notcurses yet, but do you hit upon the reason why ^[[?25h is output ?
Which value do you set to TERM environmental variable in executing mlterm? You set the same value as other terminals?

**Comment by dankamongmen** [comment]
i'm using the `mlterm` `TERM` variable. `\e[?25h` is `cnorm` in that terminfo database, which does indeed make the cursor visible. 

so, playing around with this, i've learned something interesting -- the cursor problem only seems to happen when i am not using `\e[?80l\e[?8452h` (i need to use it this way since i am on an older version of mlterm, before recent changes). when i *am* in this mode, the cursor does not seem to show back up. 

The attached log is a run both with and without my manual `cinvis` escapes.

[mlterm-log.txt](https://github.com/arakiken/mlterm/files/6721542/mlterm-log.txt)

**Comment by arakiken** [comment]
I found a bug which can cause this problem and fixed it.
Please test it.
https://github.com/arakiken/mlterm/commit/2416b7186c02c9c9af948015f68e7f32afbd2318

**Comment by dankamongmen** [comment]
looks good!

it would be awesome if you implemented `XTVERSION` with your version number in it. i'm happy to make such a patch if you'd like.

**Comment by arakiken** [comment]
I implemented.
https://github.com/arakiken/mlterm/commit/13470bb6e4de0db30998bcc6a9823b402b85d85c
The response is DCS > | mlterm(3.9.1) ST.

**Comment by dankamongmen** [comment]
wonderful! i now recognize MLterm 3.9.1+ in Notcurses, and no longer apply the cursor-hiding hack nor the inversion of DECSDM when i've verified that version. thank you!
