### ISSUE TITLE
Wayland version not launching, wrong display

### ISSUE THREAD

**Issue by TheMainMMan** [arakiken/mlterm#28]
Seems like `mlterm-wl` doesn't read `WAYLAND_DISPLAY` variable, I guess `wayland-0` is hardcoded

In msg.log I found this
`ERROR(No such file or directory): Couldn't open display wayland-0 `

This works
`mlterm-wl -d wayland-1`

```
$ echo $WAYLAND_DISPLAY
wayland-1
```

**Comment by arakiken** [comment]
Thanks.
I fixed it.
https://github.com/arakiken/mlterm/commit/c87f20d8dac141f9848570179428bf8b2cdc7689

**Comment by TheMainMMan** [comment]
Nice, it works now.
Thanks!
