### ISSUE TITLE
Cycle mlterm-wl makes labwc wayland compositor crashed.

### ISSUE THREAD

**Issue by ahmadraniri1994** [arakiken/mlterm#30]
Some days ago, I built mlterm-wl succesfully. I tried it on labwc wayland compositor and when I cycle apps or when only mlterm-wl open, it crashed labwc. I don't know if it because mlterm-wl, the wlroots, or the wayland compositor.

**Comment by ahmadraniri1994** [comment]
Log : 
[mlterm-labwc-crashed.log](https://github.com/arakiken/mlterm/files/7630190/mlterm-labwc-crashed.log)

**Comment by ahmadraniri1994** [comment]
OS : Debian unstabe.
Mlterm master.
Labwc wayland compositor master.
Wlroots 0.15 (/usr/local) and wlroots 0.13 (/usr)

**Comment by ahmadraniri1994** [comment]
Oh, turns out it is fixed by assign a name or title for mlterm, by using some mlterm's options. Since I compile mlterm my self, it must be my mistake. I'm sorry for this. Closing this issue now.

**Comment by arakiken** [comment]
Thanks.
I tried labwc 0.3.0 & wlroots 0.14.1, but starting or cycling mlterm-wl didn't make labwc crashed.
Do you specify -N option explicitly to mlterm-wl to avoid crashing labwc ?
I couldn't reproduce it but it might be caused by a bug of mlterm-wl.
