### ISSUE TITLE
Mlterm-wl always undecorated and cannot be decorated by most of wayland compositors.

### ISSUE THREAD

**Issue by ahmadraniri1994** [arakiken/mlterm#31]
Is there a way to make mlterm-wl get decorated on wayland compositors (gnome wayland / kde wayland) ?

**Comment by arakiken** [comment]
mlterm doesn't support client side decoration, so there is no way for now.
l have a plan to support xdg-decoration in the future.

**Comment by ahmadraniri1994** [comment]
Wow, Great. Thanks.

**Comment by ahmadraniri1994** [comment]
Apparently,  labwc support to decorate mlterm-wl.

**Comment by ahmadraniri1994** [comment]
closed.

**Comment by ahmadraniri1994** [comment]
Mlterm-wl seems get decorated while in float mode (swaywm) with a rule.
> for_window [app_id="mlterm"] border normal 2

**Comment by arakiken** [comment]
mlterm-wl supports xdg-decoration.
Compositors supporting xdg-decoration such as plasma(kde)-wayland decorate mlterm-wl.
https://github.com/arakiken/mlterm/commit/4798a13305bd17438608a82a60b6ff41d499a672

**Comment by ahmadraniri1994** [comment]
sorry for late reply @arakiken , I can confirm that. Thanks alot for the implementation.
