### ISSUE TITLE
macOS: input breaks output in many ways

### ISSUE THREAD

**Issue by Atemu** [arakiken/mlterm#32]
This is how mlterm looks after typing few `l`s into it on macOS 12:

<img width="836" alt="Screenshot 2022-01-16 at 18 30 06" src="https://user-images.githubusercontent.com/18599032/149670971-747fac25-756b-40fb-857c-4b0acb965cb6.png">

Safe to say, this makes mlterm unusable.

Is anyone able to reproduce this?

**Comment by arakiken** [comment]
I test mlterm-cocoa in MacOS 10.13 or before, and it works fine.
I have no machines to install MacOS 12  and it is difficult to prepare a test environment to reproduce this problem for now.

Thinking about trying to fix it in the future, can you let me make sure of some things?
* Which version do you use ? (mlterm-3.9.1 ?)
* Do you build and install it from source code?
* Does this problem happen if you remove all configurations in ~/.mlterm/ ?
* Is this screen corruption improved by selecting text with the mouse pointer?
* If you type "ls<return>", what happens?

**Comment by Atemu** [comment]
Hi, thanks for taking a look!

>  I have no machines to install MacOS 12 and it is difficult to prepare a test environment to reproduce this problem for now.

I see.

FYI, you can get a modern macOS without modern mac hardware using https://github.com/kholia/OSX-KVM from a Linux host with an AVX2-capable CPU.

* 3.9.2 but the bug also existed on 3.9.1 (tested on Catalina and Big Sur)
* Yes. Here is the Nix expression used: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/terminal-emulators/mlterm/default.nix, you don't need to fully understand it but you should get the gist.
* Yes, same issues.
* When selecting, it switches to one of the ~3 states of brokeness
* Typing ls:
  <img width="836" alt="Screenshot 2022-02-06 at 15 13 09" src="https://user-images.githubusercontent.com/18599032/152684976-c34ada60-6294-49ae-b326-7beb54a9deff.png">
  (Enter):
  <img width="836" alt="Screenshot 2022-02-06 at 15 13 33" src="https://user-images.githubusercontent.com/18599032/152684994-37f56a7b-744a-4f7d-a48e-401afa245aef.png">
  It's inconsistent though, this is what can also happen after entering `ls` (triggered by repeating it a few times):
  <img width="836" alt="Screenshot 2022-02-06 at 15 14 29" src="https://user-images.githubusercontent.com/18599032/152685036-e4682e60-3c79-440b-8733-5798d3faa063.png">

**Comment by arakiken** [comment]
Thanks.
Does this behavior change if you change "#if MAC_OS_X_VERSION_MAX_ALLOWED >= 101400" in cocoa.m to "#if 0" or "#if 1" ?
https://github.com/arakiken/mlterm/blob/master/uitoolkit/quartz/cocoa.m#L17

**Comment by Atemu** [comment]
Nothing changes unfortunately.

**Comment by Atemu** [comment]
This seems to have been a caused by our old apple SDK. Using version 11 fixes the issue.
