### ISSUE TITLE
Increase Font Size on the fly 

### ISSUE THREAD

**Issue by dripware** [arakiken/mlterm#38]
how can i increase and decrease font size of terminal temporarily with a keyboard shortcut?

**Comment by arakiken** [comment]
For example, following configuration in ~/.mlterm/key enables you to change font size temporarily by pressing F1 or F2 key.

F1="proto:fontsize=larger"
F2="proto:fontsize=smaller"

**Comment by arakiken** [comment]
Please use "plus" and "minus" instead of "+" and "-" in x11.
But it doesn't work in wayland. I'll fix it.

**Comment by linwaytin** [comment]
Thank you. That works. 

I have a related question. With `Control+Shift+plus="proto:fontsize=larger"`, I can change the font size on the fly, but I need to hit the key `Control+Shift+plus` twice to see the effect. I'm not sure if this is some subtle issue on my system, but it is related to the increment of font size. 

My system is Linux+X11. Other keybindings like `Control+Shift+V=INSERT_CLIPBOARD
` works by hitting just once, as it should be.

**Comment by arakiken** [comment]
Try to add a following line to ~/.mlterm/main.
step_in_changing_font_size = 2

**Comment by linwaytin** [comment]
Great! That solves the problem.
