### ISSUE TITLE
bug? corruption during (lots of) 24-bit ANSI escape codes

### ISSUE THREAD

**Issue by patsie75** [arakiken/mlterm#39]
I'm not very familliar with mlterm and only recently installed it to check compatibility with my awk-scripts, which output a lot of ANSI escape codes for 24-bit colors (i.e.: ESC[38;2;(r);(g);(b);48;2;(r);(g);(b)m )  
These escape codes seem to cause semi-random corruption in mlterm's output.  
An example can be found here: https://youtu.be/rXlc66Ymz_I  
When outputting the same ANSI encoded content/file multiple times, the corruption seems to be semi-randomly displayed every time. The above video shows this by 'zcat' the same file multiple times in mlterm.  

The used file (demo.frame.gz) with the ANSI encoded content, is attached to this bug-report.  
[demo.frame.gz](https://github.com/arakiken/mlterm/files/8238250/demo.frame.gz)

Please advise.

**Comment by patsie75** [comment]
Any feedback at all is appreciated

**Comment by arakiken** [comment]
Thanks.
Sorry for replying late.
I fixed it -> https://github.com/arakiken/mlterm/commit/036c7f03e06a7e69c4f9dab7f078b05ca7a3d0d7

Even if you apply this patch, the screen gets corrupt if you select it with the mouse.
If you also want to fix this problem, specify --disable-compact-truecolor option to ./configure script in building mlterm.

Regards,

**Comment by patsie75** [comment]
No need to apologize, I'm happy that you are so active in working on this project! Thank you a lot.
Indeed the corruption is now gone. So that is good news! Thank you for that!

I did notice that because of your 'compact' use of true color, the color accuracy is less than optimal. See this screenshot for example with four different terminals and the output of the same program (awk-demo) at a similar point in time.
![Screenshot from 2022-04-03 14-56-57-1](https://user-images.githubusercontent.com/32614987/161429371-5ab04e97-e5d5-4452-a0d6-74c0e0cacf8b.png)
The top-left terminal is standard compiled mlterm from the latest master branch (with your fix) Here you can clearly see color-banding happening, but performance is good.
The top-right is mlterm master branch compiled with `--disable-compact-truecolor`. The color-banding is now gone and it looks color-accurate! The only issue is that performance of displaying large amounts of (true-color) ANSI escape codes has dropped dramatically.  Sometimes more than 50%.
The bottom-left is Gnome Terminal (libvte based) and the bottom-right xterm. Both look color accurate and have great performance.

**Comment by arakiken** [comment]
Thanks.
"--vtcolor true" option improves accuracy.
I'll investigate the performance problem.

**Comment by patsie75** [comment]
Running mlterm with `--vtcolor true` really did the trick! color accuracy looks great and performance is 'good enough'. Mlterm is not as fast as Gnome Terminal or xterm, but it has a reasonable throughput (at least for my usecase :-) )
(Just in case you are interested in my usecase(s), you could try for example https://github.com/patsie75/awk-demo )
For now I will consider this report closed (the color bug has been solved). If you could squeeze some extra performance out of mlterm, I would love it, but won't blame you if have other priorities.

Thanks again for the help!
