### ISSUE TITLE
XDG Base Directory Support

### ISSUE THREAD

**Issue by Anas-Sherif** [arakiken/mlterm#42]
Anyway to move ~/.mlterm to $XDG_CONFIG_HOME/mlterm

**Comment by arakiken** [comment]
mkdir ~/.config/mlterm
Mlterm uses it only if it exists.

**Comment by Anas-Sherif** [comment]
> mkdir ~/.config/mlterm Mlterm uses it only if it exists.

It uses ~/.config not $XDG_CONFIG_HOME my $XDG_CONFIG HOME is diffrent so it doesn't work.

**Comment by arakiken** [comment]
Sorry for late  reply.
I support XDG_CONFIG_HOME.
https://github.com/arakiken/mlterm/commit/71df0714edc7715524092213516790a24178615b

**Comment by arakiken** [comment]
Some fixes.
https://github.com/arakiken/mlterm/commit/1875484930bf36d9e8200b6dfec856a8676dc7a9

**Comment by Anas-Sherif** [comment]
Thanks!
