### ISSUE TITLE
The width of scrollbar

### ISSUE THREAD

**Issue by linwaytin** [arakiken/mlterm#64]
First I really want to thank the developers for this package. It's fast, lightweight, and supports CJK. 

One problem I have is about the width of the scrollbar. Maybe because I have a HiDPI screen, the scrollbar is quite narrow. Is there a way to change the width?

Thank you.

**Comment by arakiken** [comment]
Thanks.
I added --sdpr option to determine the width of "simple" (default) scrollbar.
Starting mlterm with --sdpr 2 option doubles the width of "simple" scrollbar.
There is no way to widen scrollbars except "simple" for now.

https://github.com/arakiken/mlterm/commit/c3a20458e8e3e93cf696c8802da793105d94fab1

**Comment by linwaytin** [comment]
Thank you. I just tried it and that's indeed what I want. It would be nice to make it work for other scrollbars, since the HiDPI screens are more common and many users like me have a high-resolution setting.
