### ISSUE TITLE
Support Fcitx 5

### ISSUE THREAD

**Issue by Arfrever** [arakiken/mlterm#7]
Support for Fcitx 5 should be added.

[Fcitx 5.0.0 was released on 2020-11-03](https://groups.google.com/g/fcitx-announce/c/-A3tD9vihWk).
libFcitx5GClient library is provided by fcitx5-gtk package.

**Comment by arakiken** [comment]
l support fcitx5 experimentally.
https://github.com/arakiken/mlterm/commit/0cb3c531072b42fe9d9a2e7e1fbd1bcff89c4bf1

**Comment by Arfrever** [comment]
`Fcitx5GClient.pc` fixed to include `-lFcitx5GClient` in https://github.com/fcitx/fcitx5-gtk/commit/a4c3637d6f71803b07cd666a9a8a8d95756ed28f.

**Comment by wengxt** [comment]
Thanks for pointing out the bug in pkg-config file.

Actually @arakiken , you don't really need to include the keysym file, because XK_* is basically exactly same as fcitx, I hope that could simplify your implemenation a little bit.

**Comment by arakiken** [comment]
Thanks.

BTW, It is necessary to use the keysym file to support fcitx5 not only on mlterm (for X11) but also on mlterm-fb (for framebuffer), mlterm-sdl2 (for sdl2) and mlterm-con (terminal multiplexer).
They don't depend on Xlib and the definitions of XK_* of them are different from Xlib.

native_to_fcitx_ksym()
https://github.com/arakiken/mlterm/blob/0cb3c531072b42fe9d9a2e7e1fbd1bcff89c4bf1/inputmethod/fcitx/im_fcitx.c#L147

The definitions of XK_* on mlterm-fb, mlterm-sdl2 and mlterm-con.
https://github.com/arakiken/mlterm/blob/0cb3c531072b42fe9d9a2e7e1fbd1bcff89c4bf1/uitoolkit/fb/ui.h
https://github.com/arakiken/mlterm/blob/0cb3c531072b42fe9d9a2e7e1fbd1bcff89c4bf1/uitoolkit/sdl2/ui.h
https://github.com/arakiken/mlterm/blob/0cb3c531072b42fe9d9a2e7e1fbd1bcff89c4bf1/uitoolkit/console/ui.h
