### ISSUE TITLE
mlconfig is not built if `--with-gui=` list includes `fb`

### ISSUE THREAD

**Issue by doronbehar** [arakiken/mlterm#73]
Hello again,

Again as part of my experience with testing different `./configure` flags, I also noticed that if `--with-gui=` includes the `fb`, the `mlconfig` tool doesn't get compiled. I guess this is sort of intentional? I'm not sure what exactly it means to use use `mlterm-fb` but I guess that if you use bare Linux console and `mlterm` - you cannot use the graphical program `mlconfig`.

However, it doesn't make sense to me - what if I'd want multiple guis installed, and still be able to configure `mlterm-wl` and other guis with `mlconfig`, while still keeping `mlterm-fb`?

I think the issue is sourced here:

https://github.com/arakiken/mlterm/blob/5952b52dd4cfe11034305023bd35d299d1ca9247/configure.in#L1097-L1100

I think the conditional of 1100 is not need at all - let the user decide whether they'd want to compile `mlconfig` along with `mlterm-fb`.

**Comment by arakiken** [comment]
Thanks. I fixed.
https://github.com/arakiken/mlterm/commit/b09bdd678d4e1e61928f12369f25339346bf0d1b

**Comment by doronbehar** [comment]
Thanks @arakiken. This fixed the issue indeed.
