### ISSUE TITLE
Select text using only the keyboard

### ISSUE THREAD

**Issue by vincent-olivert-riera** [arakiken/mlterm#77]
This is just a question, not a bug or anything like that.

Does mlterm support selecting text just using the keyboard?

For instance, some terminals like termite enter in "selection mode" when you press ctrl-shift-space, and they you can control the cursor like if you were in a Vim editor, select whatever you want and copy it. (https://wiki.archlinux.org/title/termite)

Other terminals like kitty have a different approach, where you can set a keyboard shortcut to open the current terminal buffer into your desired editor, select whatever you want and copy it, exit the editor and go back to the terminal, having whatever you copied inside your clipboard. (https://github.com/kovidgoyal/kitty/issues/719)

---

EDIT

I have read this in mlterm's man:

> COPY MODE
>       mlterm enters into copy mode by typing Shift + Control  +
>       Return  key.  In  the  mode,  you  can move in the screen
>       including backlog, select region and copy it by the  fol-
>       lowing keys.

However, when I press shift-ctrl-return my mlterm does not enter in copy mode.

**Comment by arakiken** [comment]
In my environment, copy mode starts by pressing Shift+Control+Return.
If you add "F1=COPY_MODE" to ~/.mlterm/key and press F1 key, won't copy mode start?

**Comment by vincent-olivert-riera** [comment]
I'm using the version shipped with Debian Bookworm:

```
$ mlterm --version
mlterm version 3.9.0 
Features: otl ssh implugin imagelib(builtin) utmp
```

Could it be because it's old?
