### ISSUE TITLE
Error making mlterm

### ISSUE THREAD

**Issue by Unshure** [arakiken/mlterm#8]
mlterm fails after running the following commands:
```
git clone https://github.com/arakiken/mlterm.git
cd mlterm
./configure --enable-ind --enable-anti-alias --with-gtk=3.0
make
```
Error:
```
../../baselib/include/pobl/bl_util.h:64:61: error: expected expression before '[' token
 #define BL_ARRAY_SIZE(array) (sizeof(array) / sizeof((array)[0]))
```
On this line: https://github.com/arakiken/mlterm/blame/master/baselib/src/bl_util.h#L64

**Comment by arakiken** [comment]
Thanks. I fixed it.

https://github.com/arakiken/mlterm/commit/39d4493212add079a0c73d659160fb46d1d45f18
