### ISSUE TITLE
Mouse wheel scroll in man or less

### ISSUE THREAD

**Issue by linwaytin** [arakiken/mlterm#80]
I found in `man` or `less` I cannot use mouse wheel to scroll up and down. Most terminals can do this. Even `xterm` has this feature with `alternateScroll` set to `true`. 

Does `mlterm` support this feature? If so, how can I enable it?

Thank you.

**Comment by arakiken** [comment]
Thanks.
mlterm-3.9.3 or before didn't support alternate scroll mode.
https://github.com/arakiken/mlterm/commit/d5074331f13044fb1ab7b2c86c705fdea13a14c9 supports it.

**Comment by linwaytin** [comment]
Thanks for such a quick fix. Now `mlterm` has this feature!
