### ISSUE TITLE
libind fails to build with BSD make

### ISSUE THREAD

**Issue by tsutsui** [arakiken/mlterm#88]
In https://github.com/arakiken/mlterm/commit/88933d32d8357a626ce64328ea62e82d4db19292 `libind/Makefile.in` has been changed to use a rule `libind_%.la: %.o` but it looks GNU make extension and fails on BSD make:
https://github.com/tsutsui/mlterm/actions/runs/8394267307/job/22990995198#step:3:3664
```
   libtool: compile:  gcc -Wall -g -O2 -I../libind -I/usr/local/include -DLIBDIR=\"/usr/local/lib\" -c lex.split.c -o lex.split.o >/dev/null 2>&1
  ../libtool --mode=link gcc -o libind.a indian.lo keyboard.lo lex.split.lo 
  libtool: link: ar cr libind.a  indian.o keyboard.o lex.split.o
  libtool: link: ranlib libind.a
  make[1]: don't know how to make libind_assamese.la. Stop
  
  make[1]: stopped in /home/runner/work/mlterm/mlterm/libind
  *** Error code 2
  
  Stop.
```

**Comment by arakiken** [comment]
Thanks.
https://github.com/arakiken/mlterm/commit/0a0076556317962630ea21e601a98499eb830584

**Comment by tsutsui** [comment]
Confirmed. Thanks!
