### ISSUE TITLE
Emojis by png files in emoji_path are not drawn on xlib 1bpp and --with-imagelib=no

### ISSUE THREAD

**Issue by tsutsui** [arakiken/mlterm#96]
It looks mlterm built without imagelib complains on trying to print emojis:
```
mlimgloader 0 0 0 [file path] stdout (-a)
  -a: ignored.
```

Maybe `ui_load_inline_picture()` in `uitoolkit/ui_picture.c` calls `ui_imagelib_load_file()` via static `load_file()` with `keep_aspect` but in this case `load_sixel()` doesn't help for png emoji files unlike #93?

**Comment by arakiken** [comment]
mlimgloader doesn't support png files if gdk-pixbuf is not found.
This commit support png emoji files with the use of libpng 1.6 or later.
https://github.com/arakiken/mlterm/commit/0af65caa1aa6e62b6c836299c4353dca16387b56

**Comment by tsutsui** [comment]
Confirmed, at least on NetBSD/i386 10.0 and patched pkgsrc/x11/mlterm (without gdk_pixbuf2 option).
Thanks!
![mlterm-libpng-emoji](https://github.com/user-attachments/assets/a8473132-7138-49bd-a55d-d519eec19e1d)

**Comment by tsutsui** [comment]
Also confirmed on installed version:
![mlterm-libpng-emoji-2](https://github.com/user-attachments/assets/7e177ba2-8704-4b1f-999a-c2e624a3c93e)
